config/routes.rb
Menolog::Application.routes.draw do
  resources :samples

  root :to => "welcome#index"
  devise_for :users

  resources :days

end

app/models/day.rb
class Day < ActiveRecord::Base
  include TimeHack
  NONE = 0
  
  MENSES_SPOTTING = 1
  MENSES_LIGHT = 2
  MENSES_MEDIUM = 3
  MENSES_HEAVY = 4
  
  belongs_to :user
  has_one :cycle, :dependent => :destroy
  before_save :handle_cycle

  def to_param
    date.to_s
  end
  
  private
  def handle_cycle
    if first
      if cycle.nil?
        build_cycle
      end
    else 
      if !cycle.nil?
        cycle.destroy
      end
    end
  end
  
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_filter :authenticate_user!
  
  def edit
    date = Date.parse(params[:id])
    @day = current_user.day(date) || Day.new(:date=>date)
  end
  
  def update
    edit
    @day.user_id=current_user.id
    @day.update_attributes(params[:day])
    
    if "Save" === params[:commit]
      redirect_to_edit @day.date
    else
      redirect_to_edit @day.date + 1
    end
  end
  
  def destroy
    edit
    Day.delete(@day.id)
    redirect_to_edit @day.date
  end
  
  def index
    redirect_to_edit date
  end
  
  private
  def date
    params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def redirect_to_edit date
    redirect_to :controller => "days", :action => "edit", :id => date.to_s
  end
end

app/helpers/days_helper.rb
module DaysHelper
  def menses_options
    [[ "Spotting",Day::MENSES_SPOTTING],
    ["Light", Day::MENSES_LIGHT],
    ["Medium", Day::MENSES_MEDIUM],
    ["Heavy", Day::MENSES_HEAVY]]
  end
  def cf_feeling_options
    [[ "Dry",1],
    ["Humid", 2],
    ["Wet", 3],
    ["Slippery", 4]]
  end
  def cf_appearance_options
    [[ "Sticky",1],
    ["Creamy", 2],
    ["Watery", 3],
    ["Eggwhite", 4]]
  end
  def c_position_options
    [[ "Low",1],
    ["Medium", 2],
    ["High", 3]]
  end
  def c_opening_options
    [[ "Closed",1],
    ["Medium", 2],
    ["Open", 3]]
  end
  def c_texture_options
    [[ "Firm",1],
    ["Medium", 2],
    ["Soft", 3]]
  end
  def every_5_min
    (0..11).map {|m| sprintf("%02d",5*m)}
  end
end

app/views/days/edit.html.haml
#form
  - form_for :day, :url => day_path(@day), :html => {:method => :put} do |f|
    #calendar
      -#= calendar_date_select_tag "e_date", @day.date, :embedded => true, :onchange => "window.location='/days/'+ $F(this)+'/edit'"
    =f.hidden_field :date
    .group
      = f.label :temperature, 'Temperature:'
      = f.text_field  :temperature
      %br
      = f.label :time, "Time:"
      = f.select :hour, "00".."23", :include_blank => true
      \:
      = f.select :min, "00".."59", :include_blank => true
      %br
      = f.label :first, "First Day of Cycle:"
      = f.check_box :first, :class => :boxes
      %br
      = f.label :mensing, "Menses:"
      = f.select :mensing, menses_options, :include_blank => true
      %br
      = f.label :intercourse, "Intercourse:"
      = f.select :intercourse, 1..5, :include_blank => true
    .group
      .title
        Cervical Fluid
      %br
      = f.label :cervical_fluid_feeling, "Feeling:"
      = f.select :cervical_fluid_feeling, cf_feeling_options, :include_blank => true
      %br
      = f.label :cervical_fluid_feeling, "Appearance:"
      = f.select :cervical_fluid_appearance, cf_appearance_options, :include_blank => true
    .group
      .title
        Cervix
      %br
      = f.label :cervix_position, "Position:"
      = f.select :cervix_position, c_position_options, :include_blank => true
      %br
      = f.label :cervix_opening, "Opening:"
      = f.select :cervix_opening, c_opening_options, :include_blank => true
      %br
      = f.label :cervix_texture, "Texture:"
      = f.select :cervix_texture, c_texture_options, :include_blank => true
    .group
      .title
        Other
      %b
      = f.label :ovulation_pain, "Ovulation pain:"
      = f.check_box  :ovulation_pain, :class => :boxes
      %br
      = f.label :tender_breasts, "Tender breats:"
      = f.check_box  :tender_breasts, :class => :boxes
      %br
      = f.label :fever, "Fever:"
      = f.check_box :fever, :class => :boxes
      %br
      = f.label :lack_of_sleep, "Lack of Sleep:"
      = f.check_box :lack_of_sleep, :class => :boxes
    #buttons
      = submit_tag 'Save'
      = submit_tag 'Save & Next'
  #buttons
    = button_to "Cancel", :controller => "welcome", :action => "index"
    = button_to "Delete", { :action => "destroy", :id => @day }, :confirm => "Are you sure?",  :method => :delete, :disabled => @day.new_record?
#chart
  -#%img{ :src => url_for(:controller => "charts", :action => "cycle", :id => @day )}